whitespace

diff --git a/check_qemu-ga b/check_qemu-ga
--- a/check_qemu-ga
+++ b/check_qemu-ga
@@ -7,13 +7,13 @@ IGNORED_DOMAINS=("")
 [[ ! $( whoami ) == 'root' ]] && printf "must run as root.\n\n" >&2 && exit 3
 
 while getopts ":hi:" opt; do
-    case $opt in
-      i  ) IFS=';' read -r -a IGNORED_DOMAINS <<< "$OPTARG" ;;
-      :  ) error "Option -$OPTARG requires an argument." ;;
-      \? ) error "Invalid option: -$OPTARG" ;;
-      h  ) printf "Checks if qemu-agent guest-ping is responding. Run with sudo.\nUsage: $( basename $0 ) [-i '<IGNORED VMs>']\nIgnored VMs should be semicolon separated.\n\n" >&2 && exit 3 ;;
-      *  ) usage ;;
-    esac
+	case $opt in
+	  i  ) IFS=';' read -r -a IGNORED_DOMAINS <<< "$OPTARG" ;;
+	  :  ) error "Option -$OPTARG requires an argument." ;;
+	  \? ) error "Invalid option: -$OPTARG" ;;
+	  h  ) printf "Checks if qemu-agent guest-ping is responding. Run with sudo.\nUsage: $( basename $0 ) [-i '<IGNORED VMs>']\nIgnored VMs should be semicolon separated.\n\n" >&2 && exit 3 ;;
+	  *  ) usage ;;
+	esac
 done
 
 pingable() {
@@ -28,7 +28,7 @@ blacklisted() {
 ElementIn() {
 	local element match="$1"
 	shift
-	for element; do 
+	for element; do
 		[[ "$element" == "$match" ]] && return 0
 
 	done
@@ -37,7 +37,7 @@ ElementIn() {
 }
 
 
-for DOMAIN in $( virsh list --name ); do 
+for DOMAIN in $( virsh list --name ); do
 	if ! blacklisted; then
 		if pingable; then
 			SUCCESSFUL+=( $DOMAIN )
